language: python

python:
  - "3.6"

services:
  - postgresql

addons:
  postgresql: "9.6"

env:
  global:
    -
  matrix:
    - DB=postgresql

before_script:
  - psql -c 'create database travis_ci_db;' -U postgres

install:
  - pip install -r requirements.txt

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - py.test

after_success:
  - coveralls
