language: python

python:
  - "3.6"

services:
  - postgresql
#
# env:
#    matrix:
#     - Django==2.0.13 DB=postgresql

before_script:
  - psql -c 'create database travis_ci_db;' -U postgres

install:
  - pip install -r requirements.txt

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python -m pytest --cov

after_success:
- coveralls
